coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "header, diff"
  behavior: default

ignore:
  - "spec/**/*"
  - "test/**/*"
  - "vendor/**/*"
  - "db/**/*"
  - "lib/tasks/**/*"
  - "config/**/*"
  - "bin/**/*"
  - "docs/**/*"

github_checks:
  annotations: true
