default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= [ENV.fetch("RAILS_MAX_THREADS", 5).to_i, 5].max %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV["PGDATABASE"] || "coinbase_futures_bot_development" %>

test:
  <<: *default
  url: <%= ENV["TEST_DATABASE_URL"] || ENV["DATABASE_URL"] %>
  database: <%= ENV["PGDATABASE"] || "coinbase_futures_bot_test" %><%= ENV.fetch("TEST_ENV_NUMBER", "") %>

production:
  <<: *default
